CREATE TABLE veiculo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    veiculo VARCHAR(100) NOT NULL,
    marca VARCHAR(100) NOT NULL,
    ano INT NOT NULL,
    descricao TEXT,
    vendido BOOLEAN DEFAULT FALSE,
    created_veiculo DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_veiculo DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;